### ISSUE TITLE
Git checkout of branch creates warning

### ISSUE THREAD

**Issue by karianna** [Azure-Samples/quarkus-azure#9]
This might neeed to go to the docs repo but when the docs at https://learn.microsoft.com/en-us/azure/aks/howto-deploy-java-quarkus-app?tabs=az-login-terminal-bash#create-the-app-project ask you to do a git checkout 2023-07-17 then you get a warning:

```
martijnverburg@martijns-mbp quarkus-azure % git checkout 2023-07-17
Note: switching to '2023-07-17'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 370ef2b On branch edburns-msft-dd-1621318-quarkus-aks Copied from git@github.com:danieloh30/quarkus-todo-demo-app-aks.git (#3)
```

This should be mentioned in the docs to not cause alarm.

**Comment by majguo** [comment]
Hello @karianna  Doc https://learn.microsoft.com/en-us/azure/aks/howto-deploy-java-quarkus-app?tabs=az-login-terminal-bash#create-the-app-project does have mentioned the warning as below:

![image](https://github.com/Azure-Samples/quarkus-azure/assets/10357495/6c999475-f3ec-4fe6-a948-e502aba436e2)
